### ISSUE TITLE
h2o_mruby下で利用した時に、メモリリークが発生する

### ISSUE THREAD

**Issue by yseto** [matsumoto-r/mruby-geoip#1]
@matsumoto-r さん、はじめまして
https://twitter.com/yseto/status/650841200291778560 でお声がけいただいた件です

環境
- ubuntu trustty
- h2o-v1.5.0
- `h2o-v1.5.0/deps/`以下に`mruby-geoip`を配置してビルド
  - パッチ https://gist.github.com/yseto/522d56ec91a0dca98af3#file-0-geoip-patch
- dockerコンテナ https://github.com/yseto/docker-h2o

この環境で、
- https://gist.github.com/yseto/522d56ec91a0dca98af3#file-h2o-conf
- https://gist.github.com/yseto/522d56ec91a0dca98af3#file-country_denied_via_geoip-rb

上記のような組み合わせで実行したところ、1リクエストごとに以下のように、メモリ使用量が増えていきました。

```
root@226998863dfe:/app# pgrep h2o | xargs ps u
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
nobody     187 39.5  1.0 410404 21396 ?        Sl   01:39   0:00 h2o -c /h2o/h2o.conf
root@226998863dfe:/app# pgrep h2o | xargs ps u
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
nobody     187 20.2  1.6 422992 34152 ?        Sl   01:39   0:00 h2o -c /h2o/h2o.conf
root@226998863dfe:/app# pgrep h2o | xargs ps u
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
nobody     187 13.8  2.2 435580 46724 ?        Sl   01:39   0:00 h2o -c /h2o/h2o.conf
root@226998863dfe:/app# pgrep h2o | xargs ps u
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
nobody     187 10.3  2.8 448168 59320 ?        Sl   01:39   0:00 h2o -c /h2o/h2o.conf
```

取り急ぎ、https://gist.github.com/yseto/522d56ec91a0dca98af3#file-1-mruby-geoip-leak-guard-patch  というようなものをあてて、リクエストごとに破棄したところ、リークは穏やかになったのですが、リクエストごとにデータなどを破棄しているので、本来の使い方ではないと思っています。

h2oで、ngx_mrubyのmruby_access_handlerなどに相当するものがあれば、教えていただけると幸いです....
何卒、よろしくお願いいたします。

**Comment by matsumotory** [comment]
@yseto 

報告ありがとうございます！ まず同様に、 #2 にて、closeメソッドを実装しましたので、geoipオブジェクトを複数回実行する場合はやはり都度`close`していただくのが良いかと思います。

mod_mrubyやngx_mrubyではサーバ起動時に一度だけgeoipオブジェクトを作って、それをリクエスト時に使い回すという方法が可能ですが、h2oでは現状それができません。

もし`close`メソッドを使わない場合は、例えば[mruby-userdata](https://github.com/matsumoto-r/mruby-userdata)を使って、リクエスト共通のuserdataにgeoipオブジェクトをいれておいて、次のリクエスト時に該当のuserdataにgeoipオブジェクトがすでにあれば再確保はしない、などの使い方などが考えられます。

**Comment by matsumotory** [comment]
@yseto @kazuho さんに確認しましたが、起動時にオブジェクトを作っておくといった処理ができるそうです。

ref: https://twitter.com/kazuho/status/650869486845759488

**Comment by yseto** [comment]
@matsumoto-r 
早速のご対応、ありがとうございました。

h2oでも、起動時にオブジェクトを作って処理できるんですね。後ほど見てみようと思います。

**Comment by yseto** [comment]
@matsumoto-r 
書き方があやしいのですが、`close`をせずとも、リークなく動いていそうです。
https://gist.github.com/yseto/5c8b68caffa05b66777a

**Comment by matsumotory** [comment]
はい、クラス変数やグローバル変数でもやりたい事は達成できるかと思います。mruby-userdataはその辺りを隠蔽する技術なのですが、クラス変数でも十分かもしれません。

**Comment by kazuho** [comment]
:+1:

**Comment by yseto** [comment]
@matsumoto-r @kazuho 
mruby-userdataは、取り扱うデータが多くなればなるほど、便利そうですね。今後勉強させていただきます。
各位、ありがとうございました。
