### ISSUE TITLE
missing geoip_org

### ISSUE THREAD

**Issue by d6rkaiz** [matsumoto-r/mruby-geoip#3]
お疲れ様です。

nginxのgeoipにはgeoip_orgというデータがあるはずなんですが、実装されていないようです。
http://nginx.org/en/docs/http/ngx_http_geoip_module.html#geoip_org

もし可能なら実装頂ければ幸いです🙇

**Comment by matsumotory** [comment]
おお、了解です！やっておきます

**Comment by matsumotory** [comment]
@d6rkaiz #4 で @pyama86 が実装してくれました。

**Comment by d6rkaiz** [comment]
@pyama86 さん、@matsumotory さん
早速の対応ありがとうございました！

debian jessieでnginx 1.10.2 での環境でも無事取得確認できました。🙇
